apiVersion: v1
kind: Service
metadata:
  name: cloudl-client-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32000
  selector:
    app: cloudl-client
  type: NodePort
