apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudl-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudl-client
    spec:
      containers:
        - name: cloudl-client
          image: localhost/kavinduchamiran/cloudl-client:v1
          ports:
            - containerPort: 80
              name: http-port
  selector:
    matchLabels:
      app: cloudl-client
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    runAsNonRoot: false
    runAsUser: 0

