apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: localhost/mongo:4.0.4
      ports:
        - containerPort: 27017
          name: mongodb-port
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    runAsNonRoot: false
    runAsUser: 0
